# Generated by Django 4.2.3 on 2023-07-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_post_votes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='changed',
            field=models.DateTimeField(null=True),
        ),
    ]
